<?php

namespace Tortitas\DockerSDK;

class DockerSDK
{
  public function __construct()
  {
    //
  }

  public function list()
  {
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'http://localhost/v1.42/containers/create');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_UNIX_SOCKET_PATH, '/var/run/docker.sock');
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"Image\": \"alpine\", \"Cmd\": [\"echo\", \"hello world\"]}");

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
      echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);


    return [];
  }
}
