name: Fix Styles

on:
  push:
    branches: [master]

jobs:
  style:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.1

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer install
          composer dump

      - name: Fix styles
        run: vendor/bin/php-cs-fixer fix

      - name: Run style
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --format junit

      - uses: EndBug/add-and-commit@v9
